# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/psf/black
  rev: 19.10b0
  hooks:
  - id: black
    exclude: '(?x)^(junk_drawer | scripts)'
- repo: https://gitlab.com/PyCQA/flake8
  rev: 3.7.9
  hooks:
    - id: flake8
      exclude: '(?x)^(junk_drawer | scripts)'
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.740
  hooks:
    - id: mypy
      exclude: '(?x)^(junk_drawer | scripts)'