language: python
dist: xenial
python:
- '3.7'
install:
- pip install -r test_requirements.txt
- pip install -e .
script:
- flake8 turbine/
- mypy turbine/
- pytest tests --cov=turbine
after_success:
- coveralls